# permissions for end users to edit samzaapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: samzaapplication-editor-role
rules:
- apiGroups:
  - samzaoperator.samza.apache.org
  resources:
  - samzaapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - samzaoperator.samza.apache.org
  resources:
  - samzaapplications/status
  verbs:
  - get
