apiVersion: samzaoperator.samza.apache.org/v1alpha1
kind: SamzaApplication
metadata:
  name: samzaapplication-sample
spec:
  applicationInstance: 1
  image: 
    name: samza-operator
    pullPolicy: Never
  jobCoordinator:
    jobCoordinatorPorts:
      rpc: 8088
      ui: 8089
    resources:
      limits:
        memory: "2Gi"
  samzaContainer:
    replicas: 1
    resources:
      limits:
        memory: "2Gi"
